"use client";

import Link from "next/link";
import StationFuelHistory from "./FuelHistory";
import "./fuel-analytics.css";
import { useCallback, useEffect, useMemo, useState, useRef } from "react";

type Confidence="high"|"medium"|"low";
type EventType="initial"|"stable"|"estimated_sale"|"official_dispatch"|"estimated_restock"|"possible_correction"|"outlier";
type Station={id:number;name:string;address:string;zone:string;latitude:number|null;longitude:number|null;liters:number;estimatedCapacityLiters:number;capacitySource:"default"|"learned";fillPercent:number;hasSales:boolean;lastSaleAt:string|null;dispatchInProgress:boolean;dispatchAt:string|null;trackingId:number|null;sourceUpdatedAt:string|null;lastChangeLiters:number|null;eventType:EventType;estimatedHourlySales:number;autonomyHours:number|null;confidence:Confidence};
type Trend={observed_bucket:string;total:number;available:number;empty:number;selling:number;dispatches:number;total_liters:number;average_liters:number;median_liters:number;average_fill_percent:number;estimated_outflow_liters:number;estimated_restock_liters:number;index:number};
type Daily={date:string;estimatedSalesLiters:number;estimatedRestockLiters:number;restockEvents:number};
type FuelResponse={stations:Station[];trend:Trend[];daily:Daily[];sourceTime:string;observedAt:string;source:string;methodology:{official:string;estimated:string;cadenceMinutes:number};error?:string};
type Product="gasoline"|"diesel"|"premium"|"uls";
type Filter="all"|"stock"|"empty"|"selling"|"dispatch"|"restocked"|"critical";
type Order="highest"|"lowest"|"autonomy"|"recent";

const departments=[[1,"Chuquisaca"],[2,"La Paz"],[3,"Cochabamba"],[4,"Oruro"],[5,"Potosí"],[6,"Tarija"],[7,"Santa Cruz"],[8,"Beni"],[9,"Pando"]] as const;
const products:Record<Product,string>={gasoline:"Gasolina Especial",diesel:"Diésel Oil",premium:"Gasolina Premium",uls:"Diésel Oil Plus (ULS)"};
const filters:[Filter,string][]=[["all","Todas"],["stock","Con combustible"],["empty","Vacías"],["selling","Vendiendo"],["dispatch","Despacho en curso"],["restocked","Recarga detectada"],["critical","Cerca de agotarse"]];
const formatLiters=(value:number)=>`${new Intl.NumberFormat("es-BO").format(Math.round(value))} L`;
const formatCompact=(value:number)=>new Intl.NumberFormat("es-BO",{notation:"compact",maximumFractionDigits:1}).format(value);
const timeAgo=(value?:string|null)=>{if(!value)return"sin hora";const min=Math.max(0,Math.floor((Date.now()-Date.parse(value))/60000));if(min<2)return"ahora";if(min<60)return`hace ${min} min`;if(min<1440)return`hace ${Math.floor(min/60)} h`;return`hace ${Math.floor(min/1440)} d`};
const confidenceLabel:Record<Confidence,string>={low:"confianza inicial",medium:"confianza media",high:"confianza alta"};
const statusFor=(station:Station)=>station.liters===0?"empty":station.fillPercent<=20?"critical":station.fillPercent<=50?"medium":"healthy";
const autonomyLabel=(hours:number|null,confidence:Confidence)=>hours==null?"Aún sin historial suficiente":confidence==="low"?`Proyección inicial: ~${Math.max(1,Math.round(hours))} h`:hours<1?"Probablemente menos de 1 h":`Probablemente ${Math.max(1,Math.floor(hours))}–${Math.max(2,Math.ceil(hours+1))} h`;

function LiquidTank({percent,liters,compact=false}:{percent:number;liters:number;compact?:boolean}){
  const tone=liters===0?"gray":percent<=20?"red":percent<=50?"amber":"green";
  return <div className={`liquid-tank ${tone} ${compact?"compact":""}`} aria-label={`${formatLiters(liters)}, ${percent}% estimado`}><div className="tank-scale"><i/><i/><i/><i/></div><div className="tank-liquid" style={{height:`${Math.max(0,Math.min(100,percent))}%`}}/><div className="tank-reading"><b>{Math.round(percent)}%</b><small>{compact?formatLiters(liters):"capacidad estimada"}</small></div></div>;
}

export default function FuelSupplyDashboard(){
  const[department,setDepartment]=useState(2);const[product,setProduct]=useState<Product>("gasoline");const[filter,setFilter]=useState<Filter>("all");const[order,setOrder]=useState<Order>("highest");const[search,setSearch]=useState("");const[data,setData]=useState<FuelResponse|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[showAll,setShowAll]=useState(false);
  const requestId=useRef(0);
  const load=useCallback(async()=>{const id=++requestId.current;setLoading(true);setError("");setData(null);try{const response=await fetch(`/api/fuel-supply?department=${department}&product=${product}`,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error??"No se pudo consultar ANH");if(id===requestId.current)setData(body)}catch(cause){if(id===requestId.current)setError(cause instanceof Error?cause.message:"No se pudo consultar ANH")}finally{if(id===requestId.current)setLoading(false)}},[department,product]);
  useEffect(()=>{load();const timer=window.setInterval(load,5*60_000);return()=>window.clearInterval(timer)},[load]);
  const stations=data?.stations??[];const totalLiters=stations.reduce((sum,s)=>sum+s.liters,0);const capacity=stations.reduce((sum,s)=>sum+s.estimatedCapacityLiters,0);const overallPercent=capacity?Math.min(100,totalLiters/capacity*100):0;const selling=stations.filter(s=>s.hasSales).length;const empty=stations.filter(s=>s.liters===0).length;const dispatches=stations.filter(s=>s.dispatchInProgress).length;const currentTrend=data?.trend.at(-1);const supplyIndex=currentTrend?.index??0;
  const latestDay=data?.daily.at(-1);const estimatedSalesToday=latestDay?.estimatedSalesLiters??0;const estimatedRestockToday=latestDay?.estimatedRestockLiters??0;
  const filtered=useMemo(()=>{const query=search.trim().toLowerCase();const result=stations.filter(s=>{const matches=!query||`${s.name} ${s.address} ${s.zone}`.toLowerCase().includes(query);if(!matches)return false;if(filter==="stock")return s.liters>0;if(filter==="empty")return s.liters===0;if(filter==="selling")return s.hasSales;if(filter==="dispatch")return s.dispatchInProgress;if(filter==="restocked")return s.eventType==="estimated_restock"||s.eventType==="official_dispatch";if(filter==="critical")return s.liters>0&&s.fillPercent<=20;return true});return result.toSorted((a,b)=>order==="lowest"?a.liters-b.liters:order==="autonomy"?(a.autonomyHours??9999)-(b.autonomyHours??9999):order==="recent"?Date.parse(b.sourceUpdatedAt??"0")-Date.parse(a.sourceUpdatedAt??"0"):b.liters-a.liters)},[stations,search,filter,order]);
  const shown=showAll?filtered:filtered.slice(0,12);const departmentName=departments.find(([id])=>id===department)?.[1]??"Bolivia";
  return <section className="page fuel-page">
    <nav className="fuel-links"><Link href="/">CriptoPulso</Link><Link href="/combustibles/bolivia">Bolivia total · mapa y estadísticas →</Link></nav>
    <header className="fuel-hero"><div><span className="live-dot">● LITROS REPORTADOS · FUENTE ANH</span><h1>Cripto <i>Combustibles</i></h1><p>Saldos actuales por estación, autonomía y movimiento del abastecimiento explicados de forma clara.</p></div><div className="fuel-source"><small>ÚLTIMA LECTURA</small><b>{data?new Date(data.sourceTime).toLocaleTimeString("es-BO",{hour:"2-digit",minute:"2-digit"}):"—"}</b><span>Historial propio cada 15 minutos</span></div></header>
    <article className="fuel-filters panel"><label>DEPARTAMENTO<select value={department} onChange={e=>setDepartment(Number(e.target.value))}>{departments.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>PRODUCTO<select value={product} onChange={e=>setProduct(e.target.value as Product)}>{Object.entries(products).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>BUSCAR ESTACIÓN<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nombre, zona o dirección"/></label><button onClick={load} disabled={loading}>{loading?"Consultando…":"Actualizar"}</button></article>
    {error&&<div className="fuel-error">{error}</div>}
    <div className="fuel-data-legend"><span><i className="official-dot"/>DATO ANH: litros, venta y despacho</span><span><i className="estimate-dot"/>ESTIMACIÓN CRIPTOPULSO: capacidad, ventas y autonomía</span></div>
    <div className="fuel-overview"><article className="panel main-tank-card"><div><span className="panel-label">SALDO DEPARTAMENTAL REPORTADO</span><h2>{departmentName}</h2><p>{products[product]} · {stations.length} estaciones</p><div className="liter-number"><b>{formatCompact(totalLiters)}</b><span>litros totales</span></div><div className="index-pill">Índice real <b>{supplyIndex}/100</b></div></div><LiquidTank percent={overallPercent} liters={totalLiters}/><small className="tank-note">El volumen es la suma exacta reportada por ANH. El porcentaje usa capacidades estimadas por estación y producto.</small></article>
      <article className="panel fuel-kpis fuel-kpis-six"><div><small>LITROS REPORTADOS</small><b>{formatCompact(totalLiters)}</b><span>dato ANH actual</span></div><div><small>VENDIENDO AHORA</small><b>{selling}</b><span>de {stations.length} estaciones</span></div><div><small>ESTACIONES VACÍAS</small><b>{empty}</b><span>saldo reportado 0 L</span></div><div><small>DESPACHOS EN CURSO</small><b>{dispatches}</b><span>señal oficial ANH</span></div><div><small>VENTA ESTIMADA HOY</small><b>{formatCompact(estimatedSalesToday)}</b><span>por caída de saldos</span></div><div><small>RECARGA DETECTADA HOY</small><b>{formatCompact(estimatedRestockToday)}</b><span>por aumento de saldos</span></div></article></div>
    <article className="panel fuel-filter-strip"><div>{filters.map(([id,label])=><button key={id} className={filter===id?"active":""} onClick={()=>setFilter(id)}>{label}</button>)}</div><label>ORDENAR<select value={order} onChange={e=>setOrder(e.target.value as Order)}><option value="highest">Más combustible</option><option value="lowest">Menos combustible</option><option value="autonomy">Menor autonomía</option><option value="recent">Actualización reciente</option></select></label></article>
    <StationFuelHistory key={`${department}-${product}`} department={department} product={product} stations={loading?[]:stations}/>
    <article className="station-section"><div className="station-title"><div><span className="panel-label">DETALLE POR ESTACIÓN</span><h2>Saldo, ritmo y autonomía</h2></div><span>{filtered.length} resultados</span></div><div className="station-tank-grid">{shown.map(station=>{const state=statusFor(station);const mapUrl=station.latitude!=null&&station.longitude!=null?`https://www.google.com/maps/search/?api=1&query=${station.latitude},${station.longitude}`:`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${station.name}, ${station.address}, ${departmentName}, Bolivia`)}`;return <article className={`station-tank-card panel ${state}`} key={station.id}><LiquidTank percent={station.fillPercent} liters={station.liters} compact/><div className="station-body"><div className="station-events">{station.dispatchInProgress&&<span className="station-event dispatch">↻ Despacho ANH en curso</span>}{station.eventType==="estimated_restock"&&<span className="station-event restock">↑ Recarga detectada</span>}{station.hasSales?<span className="station-event sale">● Venta activa · {timeAgo(station.lastSaleAt)}</span>:<span className="station-event quiet">○ Sin venta activa</span>}</div><h3>{station.name}</h3><p>{station.address}</p><div className="station-numbers"><span><small>SALDO ANH</small><b>{formatLiters(station.liters)}</b></span><span><small>CAPACIDAD {station.capacitySource==="learned"?"APRENDIDA":"ESTIMADA"}</small><b>{formatLiters(station.estimatedCapacityLiters)}</b></span><span><small>RITMO ESTIMADO</small><b>{station.estimatedHourlySales?`${formatLiters(station.estimatedHourlySales)}/h`:"Aprendiendo"}</b></span></div><div className="autonomy"><b>{autonomyLabel(station.autonomyHours,station.confidence)}</b><span>{confidenceLabel[station.confidence]} · actualizado {timeAgo(station.sourceUpdatedAt)}</span></div><a className="station-map-link" href={mapUrl} target="_blank" rel="noopener noreferrer">⌖ Ver ubicación</a></div></article>})}</div>{filtered.length>12&&<button className="show-stations" onClick={()=>setShowAll(!showAll)}>{showAll?"Mostrar menos":`Ver las ${filtered.length} estaciones`}</button>}</article>
    <article className="panel fuel-method"><div><span className="panel-label">TRANSPARENCIA DE DATOS</span><h2>Qué sabemos y qué estimamos</h2></div><div><b>Reportado por ANH</b><p>Saldo en litros, venta activa, despacho en curso, ubicación y última actualización.</p></div><div><b>Calculado por CriptoPulso</b><p>Capacidad visual, porcentaje, salida/venta, volumen de recarga y autonomía probable.</p></div><div><b>Regla de aprendizaje</b><p>Base de 25.000 L. Un saldo superior a 26.000 L se confirma con otra lectura consistente antes de convertirse en el nuevo 100%.</p></div></article>
    <p className="fuel-disclaimer">Fuente: plataforma pública ANH Abastecimiento. Las estimaciones no son mediciones oficiales de ventas ni garantías de disponibilidad. El saldo puede cambiar durante el traslado. Consulta siempre la hora de actualización antes de decidir.</p>
  </section>;
}
