export type Guide = { slug: string; title: string; description: string; updated: string; readingMinutes: number; sections: { heading: string; paragraphs: string[]; bullets?: string[] }[] };

export const guides: Guide[] = [
  { slug: "como-interpretar-abastecimiento-combustibles", title: "Cómo interpretar el abastecimiento de combustibles en Bolivia", description: "Guía para leer saldos, ventas recientes, despachos e índice departamental sin confundir rangos con litros exactos.", updated: "2 de septiembre de 2026", readingMinutes: 7, sections: [
    { heading: "Qué información muestra CriptoPulso", paragraphs: ["El módulo de abastecimiento organiza la información pública disponible por departamento, producto y estación. Su objetivo es ayudar a identificar dónde existe una mejor probabilidad de encontrar combustible y entender si la situación general mejora o empeora.", "La fuente clasifica los saldos en rangos. CriptoPulso conserva esa clasificación, añade búsquedas, ordenamiento, ubicación y un histórico. El dibujo de un tanque no es una lectura directa del tanque físico de la estación."], bullets: ["Saldo completo: más de 15.000 litros informados.", "Saldo aceptable: entre 5.000 y 15.000 litros.", "Saldo bajo: menos de 5.000 litros.", "Sin reporte: no existe información suficiente para asignar un rango."] },
    { heading: "Cómo usar los datos antes de trasladarse", paragraphs: ["Primero selecciona departamento y producto. Después ordena las estaciones de mayor a menor saldo y confirma la hora de la última venta. Una estación con saldo completo pero sin venta reciente puede estar cerrada, actualizando información o sin actividad por otra razón; conviene leer varias señales juntas.", "El enlace de ubicación permite revisar la ruta. La disponibilidad puede cambiar mientras una persona se traslada, especialmente durante periodos de alta demanda. CriptoPulso no reserva combustible ni garantiza atención."], bullets: ["Prioriza una estación con saldo completo o aceptable.", "Comprueba si registra venta reciente.", "Observa si existe un despacho en curso.", "Ten una segunda opción cercana antes de salir."] },
    { heading: "Qué significa la evolución", paragraphs: ["Cada fotografía histórica asigna 100 puntos a saldo completo, 60 a aceptable, 20 a bajo y 0 a sin disponibilidad informada. El promedio de las estaciones forma un índice entre 0 y 100. Si varias estaciones bajan de completo a aceptable, el índice desciende; si llegan despachos y los saldos se recuperan, sube.", "Una línea plana no siempre es un error: puede significar que la clasificación de las estaciones no cambió. El índice resume rangos, por lo que una venta dentro del mismo rango no produce movimiento hasta que la estación cambia de categoría."] },
    { heading: "Límites y uso responsable", paragraphs: ["El índice es una elaboración de CriptoPulso y no una calificación oficial de la ANH. Sirve para comparar momentos y departamentos, no para estimar inventarios nacionales ni calcular litros almacenados. Debe leerse con la fecha, hora y cantidad de estaciones incluidas.", "Fuente primaria: aplicación ANH Abastecimiento. Análisis, visualización e histórico: CriptoPulso. Si una estación detecta un dato incorrecto, puede comunicarlo mediante la página de contacto."] }
  ]},
  { slug: "dolar-oficial-y-p2p-bolivia", title: "Dólar oficial y precio P2P en Bolivia: diferencias y riesgos", description: "Explicación práctica para no mezclar el tipo de cambio oficial con precios publicados entre usuarios.", updated: "2 de septiembre de 2026", readingMinutes: 6, sections: [
    { heading: "Dos referencias que no significan lo mismo", paragraphs: ["El tipo de cambio oficial es una referencia institucional. Un precio P2P proviene de ofertas entre compradores y vendedores en una plataforma y puede variar por método de pago, monto, liquidez, reputación y hora. Compararlos puede mostrar una brecha, pero no convierte al P2P en un nuevo tipo oficial.", "Una oferta visible tampoco garantiza que toda persona pueda operar el monto anunciado ni que el precio final sea idéntico. Los límites y condiciones del anunciante importan."] },
    { heading: "Cómo leer compra y venta", paragraphs: ["Compra y venta dependen de la perspectiva. Antes de usar cualquier cifra, identifica quién compra la moneda, quién la vende y qué activo se intercambia. En un mercado P2P también debes revisar comisiones indirectas, banco aceptado y tiempo de liberación.", "CriptoPulso presenta estas referencias con fecha y fuente para fines educativos. No ejecuta cambios de moneda ni intermedia pagos."], bullets: ["No uses una captura antigua como precio actual.", "Compara ofertas con condiciones semejantes.", "Evita transferir fuera del sistema de protección de la plataforma.", "Nunca compartas códigos de autenticación."] },
    { heading: "Qué puede explicar una brecha", paragraphs: ["Una diferencia puede relacionarse con oferta y demanda, disponibilidad de medios de pago, expectativas, controles, costos operativos y percepción de riesgo. Una sola causa rara vez explica todo el movimiento.", "Para analizar una tendencia conviene observar varios días y no solamente el último valor. También se debe separar una variación real de un cambio en la muestra de anuncios consultados."] },
    { heading: "Decisiones prudentes", paragraphs: ["Define para qué necesitas la referencia: presupuesto, comparación histórica o una operación concreta. Si la decisión implica ahorro familiar o montos relevantes, contrasta información y conserva comprobantes. Esta guía no es asesoramiento financiero ni una recomendación de compra o venta."] }
  ]},
  { slug: "precios-canasta-familiar-como-comparar", title: "Cómo comparar precios de la canasta familiar sin engañarse", description: "Método para comparar mercados, unidades, fechas y aportes comunitarios de forma responsable.", updated: "2 de septiembre de 2026", readingMinutes: 6, sections: [
    { heading: "La unidad es parte del precio", paragraphs: ["Comparar dos importes solo es válido cuando representan la misma cantidad y una calidad semejante. Un precio por kilogramo no puede enfrentarse directamente con otro por libra, arroba, bolsa o unidad. En productos envasados también importa el contenido neto.", "CriptoPulso normaliza cada registro con una unidad visible. Cuando un dato es estimado se identifica como referencial y no oficial; los aportes comunitarios se publican únicamente después de revisión."] },
    { heading: "Fecha, ciudad y establecimiento", paragraphs: ["Los alimentos pueden cambiar de precio por temporada, transporte, disponibilidad y zona. Por eso cada dato útil debe incluir fecha de compra, ciudad y mercado o comercio. Un promedio nacional es una orientación, no el precio que toda familia encontrará.", "Para planificar una compra conviene filtrar el departamento, revisar datos recientes y observar mínimo, máximo y promedio. El valor más bajo puede corresponder a otra calidad o presentación."] },
    { heading: "Cómo aportar un precio de calidad", paragraphs: ["Un aporte debe reflejar una compra u observación real y reciente. Es importante escribir el nombre reconocible del lugar, elegir el producto correcto y evitar redondeos exagerados. No se deben publicar datos personales de vendedores o compradores."], bullets: ["Registra el precio pagado, no una expectativa.", "Indica la unidad exacta.", "Usa la fecha real de compra.", "No dupliques el mismo reporte."] },
    { heading: "Qué significa una estimación", paragraphs: ["Una estimación inicial permite explorar la herramienta cuando aún no existen suficientes reportes verificados. No debe atribuirse a un mercado concreto ni presentarse como medición oficial.", "La metodología visible ayuda a conocer qué proviene de una fuente, qué fue reportado por la comunidad y qué cálculo realizó CriptoPulso."] }
  ]},
  { slug: "riesgo-criptomonedas-principiantes", title: "Gestión de riesgo en criptomonedas para principiantes", description: "Introducción educativa al tamaño de posición, invalidación, pérdidas y práctica con dinero virtual.", updated: "2 de septiembre de 2026", readingMinutes: 7, sections: [
    { heading: "Primero protege el capital", paragraphs: ["Una operación no se vuelve segura porque una señal diga compra. Las criptomonedas pueden moverse rápidamente y una pérdida grande exige una ganancia porcentual todavía mayor para recuperar el capital. La primera decisión es cuánto aceptarías perder, no cuánto esperas ganar.", "Practicar con dinero virtual permite comprobar si una regla es clara antes de exponer ahorros reales. El resultado útil no es solo ganar: también es respetar el plan."] },
    { heading: "Invalidación y stop", paragraphs: ["La invalidación es el nivel o condición que demuestra que la idea inicial dejó de ser válida. El stop se coloca a partir de esa lógica y luego se calcula el tamaño de la posición. Elegir primero un monto grande y acomodar después el stop suele producir un riesgo incoherente.", "Un stop tampoco garantiza el precio exacto de salida durante alta volatilidad o baja liquidez. Es una herramienta de control, no un seguro."] },
    { heading: "Diversificación y concentración", paragraphs: ["Comprar muchos tokens similares no necesariamente diversifica: pueden reaccionar al mismo evento y caer juntos. También existe riesgo de plataforma, stablecoin, red y custodia. Separar estos riesgos ayuda a entender qué podría fallar.", "Nunca uses dinero destinado a vivienda, alimentos, salud, deudas o emergencias. Evita apalancamiento mientras no comprendas liquidación, margen y costos."] },
    { heading: "Un diario mejora las decisiones", paragraphs: ["Antes de practicar, registra activo, motivo, entrada, invalidación, objetivo y pérdida máxima. Después anota si respetaste la regla y qué emoción influyó. Diez operaciones documentadas enseñan más que una entrada aislada.", "El simulador de CriptoPulso es educativo, utiliza capital virtual y no ejecuta operaciones reales. Ninguna señal del sitio constituye asesoramiento financiero."] }
  ]},
  { slug: "evitar-estafas-cripto", title: "Cómo reconocer y evitar estafas con criptomonedas", description: "Señales de alerta, protección de claves y pasos inmediatos ante una cuenta comprometida.", updated: "2 de septiembre de 2026", readingMinutes: 6, sections: [
    { heading: "Promesas que deben encender una alerta", paragraphs: ["Rentabilidad garantizada, presión para depositar hoy y supuestos asesores que escriben por privado son patrones comunes. El fraude suele combinar una historia convincente con urgencia para impedir que la víctima verifique.", "Una captura de ganancias, un grupo numeroso o una celebridad en video no demuestran legitimidad. Las imágenes y voces pueden ser manipuladas."] },
    { heading: "La frase semilla nunca se comparte", paragraphs: ["Quien conoce la frase semilla puede controlar la wallet. Ningún soporte legítimo necesita pedirla para resolver un problema. Tampoco debe escribirse en formularios recibidos por mensaje ni almacenarse como captura en la nube.", "Verifica el dominio letra por letra, instala aplicaciones desde su fuente oficial y activa autenticación de dos factores. Una contraseña diferente para cada servicio limita el daño de una filtración."] },
    { heading: "Operaciones P2P", paragraphs: ["Mantén la conversación y el pago dentro de las reglas de la plataforma. Confirma el abono en tu propia cuenta; no confíes solo en un comprobante enviado. No liberes activos por presión y utiliza contrapartes con historial suficiente."], bullets: ["Desconfía de pagos de terceros no acordados.", "No aceptes cambiar de canal para evitar controles.", "Guarda conversación, identificadores y comprobantes.", "Detén la operación si los datos no coinciden."] },
    { heading: "Si sospechas un incidente", paragraphs: ["Detén transferencias, cambia credenciales desde un equipo seguro, cierra sesiones y revoca permisos sospechosos. Documenta direcciones, transacciones, perfiles y horarios antes de que desaparezcan. Contacta a la plataforma y a las autoridades competentes.", "CriptoPulso no solicita frases semilla, claves privadas ni transferencias para habilitar soporte."] }
  ]}
];
export function getGuide(slug: string) { return guides.find((guide) => guide.slug === slug); }
